language: go

go:
  - 1.15.4

env: GO111MODULE=on
arch:
  - amd64
  - arm64-graviton2
virt: lxd
group: edge
os:
  - linux

script: sh scripts/build.sh $TRAVIS_OS_NAME $TRAVIS_CPU_ARCH

jobs:
  include:
    - stage: "Unit Tests"
      arch:
        - amd64
        - arm64-graviton2
      virt: lxd
      group: edge
      os:
        - linux
      script:
        - make test

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: builds/*
  skip_cleanup: true
  on:
      repo: webp-sh/webp_server_go
      tags: true
      branch: master

after_success:
  - bash <(curl -s https://codecov.io/bash)
